/**
 * Tests for server/routes/workspace-creators.js
 *
 * Covers:
 * 1. Pure builder functions — className/packageJson/metadata/agentSource/systemPrompt/readme
 * 2. initializeAgentCreatorWorkspace — full file-system integration with temp dirs
 * 3. initializeFeatureCreatorWorkspace — validation paths (reject before external CLI call)
 * 4. setupWorkspaceCreatorRoutes — route registration verification
 *
 * These tests verify the Phase 10 extraction from server.js is behavior-preserving.
 */

import { describe, it, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import { join } from 'path';
import { mkdtempSync, mkdirSync, rmSync, statSync, readFileSync } from 'fs';
import { tmpdir } from 'os';

import {
  buildGeneratedAgentClassName,
  buildAgentWorkspacePackageJson,
  buildAgentWorkspaceMetadata,
  buildAgentWorkspaceAgentSource,
  buildAgentWorkspaceSystemPrompt,
  buildAgentWorkspaceReadme,
  initializeAgentCreatorWorkspace,
  initializeFeatureCreatorWorkspace,
  setupWorkspaceCreatorRoutes,
} from '../server/routes/workspace-creators.js';

// ── buildGeneratedAgentClassName ──────────────────────────────────────────────

describe('buildGeneratedAgentClassName', () => {
  it('converts hyphenated name to PascalCase', () => {
    assert.strictEqual(buildGeneratedAgentClassName('my-cool-agent'), 'MyCoolAgent');
  });

  it('handles single word', () => {
    assert.strictEqual(buildGeneratedAgentClassName('bot'), 'Bot');
  });

  it('handles multi-hyphen', () => {
    assert.strictEqual(buildGeneratedAgentClassName('a-b-c-d'), 'ABCD');
  });

  it('falls back to GeneratedAgent for empty string', () => {
    assert.strictEqual(buildGeneratedAgentClassName(''), 'GeneratedAgent');
  });

  it('falls back to GeneratedAgent for null/undefined', () => {
    assert.strictEqual(buildGeneratedAgentClassName(null), 'GeneratedAgent');
    assert.strictEqual(buildGeneratedAgentClassName(undefined), 'GeneratedAgent');
  });

  it('handles leading/trailing hyphens', () => {
    assert.strictEqual(buildGeneratedAgentClassName('-test-'), 'Test');
  });

  it('handles numbers in name', () => {
    assert.strictEqual(buildGeneratedAgentClassName('bot-3000'), 'Bot3000');
  });
});

// ── buildAgentWorkspacePackageJson ────────────────────────────────────────────

describe('buildAgentWorkspacePackageJson', () => {
  it('returns correct package structure', () => {
    const pkg = buildAgentWorkspacePackageJson('my-agent');
    assert.strictEqual(pkg.name, '@local/my-agent');
    assert.strictEqual(pkg.version, '0.1.0');
    assert.strictEqual(pkg.private, true);
    assert.strictEqual(pkg.type, 'module');
    assert.strictEqual(pkg.description, 'my-agent generated by AgentDevClaw agent creator');
    assert.strictEqual(pkg.scripts.start, 'node agent.js');
    assert.strictEqual(pkg.engines.node, '>=20');
  });

  it('includes core agent dependencies', () => {
    const pkg = buildAgentWorkspacePackageJson('test-bot');
    assert.ok(pkg.dependencies.agentdev, 'should depend on agentdev');
    assert.ok(pkg.dependencies['@agentdev/audit-feature']);
    assert.ok(pkg.dependencies['@agentdev/shell-feature']);
    assert.ok(pkg.dependencies['@agentdev/websearch-feature']);
  });

  it('uses agent name in scoped package name', () => {
    const pkg = buildAgentWorkspacePackageJson('weather-helper');
    assert.strictEqual(pkg.name, '@local/weather-helper');
  });
});

// ── buildAgentWorkspaceMetadata ───────────────────────────────────────────────

describe('buildAgentWorkspaceMetadata', () => {
  it('returns complete metadata structure', () => {
    const meta = buildAgentWorkspaceMetadata('my-agent', 'Do stuff');
    assert.strictEqual(meta.id, 'my-agent');
    assert.strictEqual(meta.kind, 'agent');
    assert.strictEqual(meta.name, 'MyAgent');
    assert.strictEqual(meta.description, 'Do stuff');
    assert.strictEqual(meta.version, '0.1.0');
    assert.strictEqual(meta.icon, 'bot');
    assert.strictEqual(meta.category, 'custom');
    assert.strictEqual(meta.enabled, true);
  });

  it('includes all default features', () => {
    const meta = buildAgentWorkspaceMetadata('test', 'goal');
    const expectedFeatures = ['todo', 'audit', 'shell', 'websearch', 'user-input', 'mcp', 'skill'];
    assert.deepStrictEqual(meta.features, expectedFeatures);
  });

  it('includes UI entry and tabs', () => {
    const meta = buildAgentWorkspaceMetadata('test', 'goal');
    assert.strictEqual(meta.ui.entry, 'home');
    assert.ok(Array.isArray(meta.ui.tabs));
    assert.strictEqual(meta.ui.tabs.length, 2);
    const tabIds = meta.ui.tabs.map((t) => t.id);
    assert.ok(tabIds.includes('home'));
    assert.ok(tabIds.includes('chat'));
  });

  it('includes home blocks (hero + session-list)', () => {
    const meta = buildAgentWorkspaceMetadata('test', 'goal');
    assert.ok(Array.isArray(meta.ui.home.blocks));
    assert.strictEqual(meta.ui.home.blocks.length, 2);
    const blockIds = meta.ui.home.blocks.map((b) => b.id);
    assert.ok(blockIds.includes('hero'));
    assert.ok(blockIds.includes('session-list'));
  });

  it('uses goal in hero body', () => {
    const meta = buildAgentWorkspaceMetadata('bot', 'My specific goal');
    const hero = meta.ui.home.blocks.find((b) => b.id === 'hero');
    assert.strictEqual(hero.body.zh, 'My specific goal');
    assert.strictEqual(hero.body.en, 'My specific goal');
  });

  it('falls back to default description when no goal', () => {
    const meta = buildAgentWorkspaceMetadata('bot', '');
    assert.ok(meta.description.includes('generated by AgentDevClaw'));
    const hero = meta.ui.home.blocks.find((b) => b.id === 'hero');
    assert.ok(hero.body.zh.length > 0);
  });

  it('uses displayName for hero title', () => {
    const meta = buildAgentWorkspaceMetadata('cool-bot', 'goal');
    const hero = meta.ui.home.blocks.find((b) => b.id === 'hero');
    assert.strictEqual(hero.title.zh, 'CoolBot');
    assert.strictEqual(hero.title.en, 'CoolBot');
  });
});

// ── buildAgentWorkspaceAgentSource ────────────────────────────────────────────

describe('buildAgentWorkspaceAgentSource', () => {
  it('generates valid JavaScript with correct class name', () => {
    const src = buildAgentWorkspaceAgentSource('my-agent', 'goal');
    assert.ok(src.includes('class MyAgentAgent extends BasicAgent'));
  });

  it('includes all required imports', () => {
    const src = buildAgentWorkspaceAgentSource('test', 'goal');
    assert.ok(src.includes("from 'agentdev'"), 'should import from agentdev');
    assert.ok(src.includes("from '@agentdev/audit-feature'"));
    assert.ok(src.includes("from '@agentdev/shell-feature'"));
    assert.ok(src.includes("from '@agentdev/websearch-feature'"));
    assert.ok(src.includes('BasicAgent'));
    assert.ok(src.includes('TemplateComposer'));
    assert.ok(src.includes('TodoFeature'));
    assert.ok(src.includes('UserInputFeature'));
  });

  it('includes __dirname and PROMPTS_DIR setup', () => {
    const src = buildAgentWorkspaceAgentSource('test', 'goal');
    assert.ok(src.includes('const __filename = fileURLToPath(import.meta.url)'));
    assert.ok(src.includes('const __dirname = dirname(__filename)'));
    assert.ok(src.includes('const PROMPTS_DIR = join(__dirname'));
    assert.ok(src.includes('const SYSTEM_PROMPT_PATH = join(PROMPTS_DIR'));
  });

  it('instantiates all features in constructor', () => {
    const src = buildAgentWorkspaceAgentSource('test', 'goal');
    assert.ok(src.includes('new TodoFeature'));
    assert.ok(src.includes('new AuditFeature'));
    assert.ok(src.includes('new WebSearchFeature'));
    assert.ok(src.includes('new ShellFeature'));
    assert.ok(src.includes('new UserInputFeature'));
  });

  it('sets system prompt via TemplateComposer in onInitiate', () => {
    const src = buildAgentWorkspaceAgentSource('test', 'goal');
    assert.ok(src.includes('async onInitiate'));
    assert.ok(src.includes('setSystemPrompt'));
    assert.ok(src.includes('new TemplateComposer'));
    assert.ok(src.includes('{ file: SYSTEM_PROMPT_PATH }'));
    assert.ok(src.includes('{ skills:'));
  });

  it('embeds goal as JSON string', () => {
    const goal = 'You are a helpful assistant';
    const src = buildAgentWorkspaceAgentSource('test-bot', goal);
    assert.ok(src.includes(JSON.stringify(goal)));
  });

  it('generates syntactically valid JS (can be parsed by vm)', () => {
    const src = buildAgentWorkspaceAgentSource('valid-bot', 'test goal');
    // Quick smoke: verify no obvious syntax issues
    assert.ok(src.trim().endsWith('}'));
    assert.ok(src.includes('export class'));
  });
});

// ── buildAgentWorkspaceSystemPrompt ───────────────────────────────────────────

describe('buildAgentWorkspaceSystemPrompt', () => {
  it('includes header with display name', () => {
    const prompt = buildAgentWorkspaceSystemPrompt('my-agent', 'goal');
    assert.ok(prompt.includes('# MyAgent'));
  });

  it('includes agent name in backticks', () => {
    const prompt = buildAgentWorkspaceSystemPrompt('my-agent', 'goal');
    assert.ok(prompt.includes('`my-agent`'));
  });

  it('includes goal in target section', () => {
    const prompt = buildAgentWorkspaceSystemPrompt('bot', 'Build weather apps');
    assert.ok(prompt.includes('Build weather apps'));
  });

  it('includes default constraints section', () => {
    const prompt = buildAgentWorkspaceSystemPrompt('bot', 'goal');
    assert.ok(prompt.includes('## 默认约束'));
    assert.ok(prompt.includes('先澄清用户意图'));
  });

  it('falls back to default goal when empty', () => {
    const prompt = buildAgentWorkspaceSystemPrompt('bot', '');
    assert.ok(prompt.includes('根据用户后续要求继续完善'));
  });
});

// ── buildAgentWorkspaceReadme ─────────────────────────────────────────────────

describe('buildAgentWorkspaceReadme', () => {
  it('includes agent name as title', () => {
    const readme = buildAgentWorkspaceReadme('my-bot', 'goal');
    assert.ok(readme.includes('# my-bot'));
  });

  it('includes goal', () => {
    const readme = buildAgentWorkspaceReadme('bot', 'Do cool things');
    assert.ok(readme.includes('Do cool things'));
  });

  it('lists initial structure files', () => {
    const readme = buildAgentWorkspaceReadme('bot', 'goal');
    assert.ok(readme.includes('agent.js'));
    assert.ok(readme.includes('metadata.json'));
    assert.ok(readme.includes('system.md'));
    assert.ok(readme.includes('package.json'));
  });

  it('falls back to 待补充 when no goal', () => {
    const readme = buildAgentWorkspaceReadme('bot', '');
    assert.ok(readme.includes('待补充'));
  });
});

// ── initializeAgentCreatorWorkspace (integration) ─────────────────────────────

describe('initializeAgentCreatorWorkspace', () => {
  let tempRoot;

  beforeEach(() => {
    tempRoot = mkdtempSync(join(tmpdir(), 'claw-agent-init-'));
  });

  afterEach(() => {
    rmSync(tempRoot, { recursive: true, force: true });
  });

  it('creates all expected files in the output directory', async () => {
    const result = await initializeAgentCreatorWorkspace('test-agent', tempRoot, 'My goal');

    assert.strictEqual(result.agentName, 'test-agent');
    assert.strictEqual(result.parentDir, tempRoot);

    // Verify all files exist
    for (const file of result.files) {
      const filePath = join(result.outputDir, file);
      const stat = statSync(filePath);
      assert.ok(stat.isFile(), `Expected file to exist: ${file}`);
    }

    // Verify .agentdev/prompts/system.md specifically (nested path)
    const promptPath = join(result.outputDir, '.agentdev', 'prompts', 'system.md');
    assert.ok(statSync(promptPath).isFile(), 'system.md should exist');
  });

  it('writes correct package.json content', async () => {
    const result = await initializeAgentCreatorWorkspace('pkg-test', tempRoot, 'goal');
    const pkg = JSON.parse(readFileSync(join(result.outputDir, 'package.json'), 'utf8'));
    assert.strictEqual(pkg.name, '@local/pkg-test');
    assert.strictEqual(pkg.type, 'module');
    assert.ok(pkg.dependencies.agentdev);
  });

  it('writes correct metadata.json content', async () => {
    const result = await initializeAgentCreatorWorkspace('meta-test', tempRoot, 'Special goal');
    const meta = JSON.parse(readFileSync(join(result.outputDir, 'metadata.json'), 'utf8'));
    assert.strictEqual(meta.id, 'meta-test');
    assert.strictEqual(meta.name, 'MetaTest');
    assert.strictEqual(meta.description, 'Special goal');
    assert.deepStrictEqual(meta.features, ['todo', 'audit', 'shell', 'websearch', 'user-input', 'mcp', 'skill']);
  });

  it('writes agent.js with correct class name', async () => {
    const result = await initializeAgentCreatorWorkspace('code-test', tempRoot, 'goal');
    const src = readFileSync(join(result.outputDir, 'agent.js'), 'utf8');
    assert.ok(src.includes('class CodeTestAgent extends BasicAgent'));
  });

  it('writes system.md with goal', async () => {
    const result = await initializeAgentCreatorWorkspace('prompt-test', tempRoot, 'Be helpful');
    const prompt = readFileSync(join(result.outputDir, '.agentdev', 'prompts', 'system.md'), 'utf8');
    assert.ok(prompt.includes('# PromptTest'));
    assert.ok(prompt.includes('Be helpful'));
  });

  it('writes README.md', async () => {
    const result = await initializeAgentCreatorWorkspace('readme-test', tempRoot, 'goal');
    const readme = readFileSync(join(result.outputDir, 'README.md'), 'utf8');
    assert.ok(readme.includes('# readme-test'));
  });

  it('creates project docset directory structure', async () => {
    const result = await initializeAgentCreatorWorkspace('docset-test', tempRoot, 'goal');
    // PROJECT_DOCSET_SUBPATH = .agentdev/claw-workspace
    const docsetDir = join(result.outputDir, '.agentdev', 'claw-workspace');
    assert.ok(statSync(docsetDir).isDirectory(), 'project docset dir should exist');
    const projectFile = join(docsetDir, 'project.json');
    const projectRecord = JSON.parse(readFileSync(projectFile, 'utf8'));
    assert.strictEqual(projectRecord.workspaceId, 'agent-creator');
    assert.strictEqual(projectRecord.projectType, 'agent');
    assert.strictEqual(projectRecord.projectName, 'docset-test');
  });

  it('rejects invalid agent name with 400', async () => {
    await assert.rejects(
      () => initializeAgentCreatorWorkspace('Invalid Name!', tempRoot, 'goal'),
      (err) => {
        assert.strictEqual(err.statusCode, 400);
        assert.ok(err.message.includes('Invalid agent name'));
        return true;
      },
    );
  });

  it('rejects non-existent parent directory with 400', async () => {
    const fakeDir = join(tempRoot, 'does-not-exist');
    await assert.rejects(
      () => initializeAgentCreatorWorkspace('test-agent', fakeDir, 'goal'),
      (err) => {
        assert.strictEqual(err.statusCode, 400);
        assert.ok(err.message.includes('Parent directory does not exist'));
        return true;
      },
    );
  });

  it('rejects already-existing output directory with 409', async () => {
    // Pre-create the output dir
    mkdirSync(join(tempRoot, 'existing-agent'));
    await assert.rejects(
      () => initializeAgentCreatorWorkspace('existing-agent', tempRoot, 'goal'),
      (err) => {
        assert.strictEqual(err.statusCode, 409);
        assert.ok(err.message.includes('already exists'));
        return true;
      },
    );
  });

  it('rejects empty agent name', async () => {
    await assert.rejects(
      () => initializeAgentCreatorWorkspace('', tempRoot, 'goal'),
      (err) => {
        assert.strictEqual(err.statusCode, 400);
        return true;
      },
    );
  });

  it('handles missing goal gracefully', async () => {
    const result = await initializeAgentCreatorWorkspace('no-goal', tempRoot, '');
    assert.strictEqual(result.agentName, 'no-goal');
    // Files should still be created
    assert.ok(statSync(join(result.outputDir, 'agent.js')).isFile());
  });
});

// ── initializeFeatureCreatorWorkspace (validation paths) ─────────────────────

describe('initializeFeatureCreatorWorkspace', () => {
  let tempRoot;

  beforeEach(() => {
    tempRoot = mkdtempSync(join(tmpdir(), 'claw-feature-init-'));
  });

  afterEach(() => {
    rmSync(tempRoot, { recursive: true, force: true });
  });

  it('rejects invalid feature name with 400', async () => {
    await assert.rejects(
      () => initializeFeatureCreatorWorkspace('Bad_Name', tempRoot),
      (err) => {
        assert.strictEqual(err.statusCode, 400);
        assert.ok(err.message.includes('Invalid feature name'));
        return true;
      },
    );
  });

  it('rejects non-existent parent directory with 400', async () => {
    const fakeDir = join(tempRoot, 'no-such-dir');
    await assert.rejects(
      () => initializeFeatureCreatorWorkspace('valid-name', fakeDir),
      (err) => {
        assert.strictEqual(err.statusCode, 400);
        assert.ok(err.message.includes('Parent directory does not exist'));
        return true;
      },
    );
  });

  it('rejects already-existing output directory with 409', async () => {
    // resolveFeatureCreatorOutputDir appends featureName to parentDir
    mkdirSync(join(tempRoot, 'existing-feat'));
    await assert.rejects(
      () => initializeFeatureCreatorWorkspace('existing-feat', tempRoot),
      (err) => {
        assert.strictEqual(err.statusCode, 409);
        assert.ok(err.message.includes('already exists'));
        return true;
      },
    );
  });

  it('rejects empty feature name', async () => {
    await assert.rejects(
      () => initializeFeatureCreatorWorkspace('', tempRoot),
      (err) => {
        assert.strictEqual(err.statusCode, 400);
        return true;
      },
    );
  });
});

// ── setupWorkspaceCreatorRoutes ───────────────────────────────────────────────

describe('setupWorkspaceCreatorRoutes', () => {
  it('registers both creator routes on the app', () => {
    const registeredRoutes = [];

    const mockApp = {
      post(routePath, ...handlers) {
        registeredRoutes.push(routePath);
      },
    };

    const mockExpress = {
      json: () => (_req, _res, next) => next(),
    };

    setupWorkspaceCreatorRoutes(mockApp, mockExpress);

    assert.ok(registeredRoutes.includes('/protoclaw/feature_creator/initialize'));
    assert.ok(registeredRoutes.includes('/protoclaw/agent_creator/initialize'));
    assert.strictEqual(registeredRoutes.length, 2, 'should register exactly 2 routes');
  });

  it('route handlers call express.json() middleware', () => {
    let jsonMiddlewareCalled = false;

    const mockApp = {
      post(_routePath, middleware, _handler) {
        // Call the middleware to verify it's the express.json() result
        if (typeof middleware === 'function') {
          middleware({}, {}, () => {
            jsonMiddlewareCalled = true;
          });
        }
      },
    };

    const mockExpress = {
      json: () => (_req, _res, next) => next(),
    };

    setupWorkspaceCreatorRoutes(mockApp, mockExpress);

    // express.json() should have been called to produce the middleware
    assert.ok(jsonMiddlewareCalled, 'express.json() middleware should be invoked');
  });
});
